#spring:
#  datasource:
#    url: jdbc:mysql://47.107.162.1:3306/zy03?characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: zy3-1
#    password: 1QAZasdf%

#服务端口
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/class?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.tpg.cms.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
